#!/bin/sh
#
# A script to clean up the action of autogen.sh

echo
echo "**************************"
echo "* autogen.sh undo script *"
echo "**************************"
echo

echo "Remove autom4te.cache directory"
rm -rf autom4te.cache

echo "Remove configure script"
rm -f configure

echo "Remove Makefile.in files"
find . -type f -name 'Makefile.in' -exec rm {} \;

echo "Remove files generated by libtoolize"
rm -f bin/ltmain.sh
rm -f m4/libtool.m4
rm -f m4/ltoptions.m4
rm -f m4/ltsugar.m4
rm -f m4/ltversion.m4
rm -f m4/lt~obsolete.m4

echo "Remove files generated by automake"
rm -f bin/compile
rm -f bin/config.guess
rm -f bin/config.sub
rm -f bin/install-sh
rm -f bin/missing
rm -f bin/test-driver
rm -f bin/depcomp

echo "Remove remaining generated files"
rm -f aclocal.m4
rm -f config.h.in

